#!/usr/bin/env python3
"""Bundle every chNN.json file beside this script for offline browser use."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
CHAPTER_PATTERN = re.compile(r"^ch(\d{2})\.json$")
OUTPUT = ROOT / "quiz-data.js"
VALID_DIFFICULTIES = {"easy", "medium", "hard"}


def load_chapters() -> list[dict]:
    files = sorted(
        (path for path in ROOT.iterdir() if CHAPTER_PATTERN.match(path.name)),
        key=lambda path: int(CHAPTER_PATTERN.match(path.name).group(1)),
    )
    if not files:
        raise SystemExit("No chapter files found (expected chNN.json).")

    chapters: list[dict] = []
    seen_ids: set[str] = set()
    for path in files:
        file_chapter = int(CHAPTER_PATTERN.match(path.name).group(1))
        try:
            chapter = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise SystemExit(f"Could not read {path.name}: {exc}") from exc

        required = {"chapter", "chapterTitle", "questions"}
        if not isinstance(chapter, dict) or not required.issubset(chapter):
            raise SystemExit(f"{path.name}: expected keys {sorted(required)}")
        if chapter["chapter"] != file_chapter:
            raise SystemExit(
                f"{path.name}: chapter is {chapter['chapter']}, expected {file_chapter}"
            )
        if not isinstance(chapter["questions"], list):
            raise SystemExit(f"{path.name}: questions must be an array")

        for index, question in enumerate(chapter["questions"], start=1):
            label = f"{path.name} question {index}"
            needed = {"id", "difficulty", "question", "options", "answer", "explanation"}
            if not isinstance(question, dict) or not needed.issubset(question):
                raise SystemExit(f"{label}: expected keys {sorted(needed)}")
            if question["id"] in seen_ids:
                raise SystemExit(f"{label}: duplicate id {question['id']!r}")
            seen_ids.add(question["id"])
            if question["difficulty"] not in VALID_DIFFICULTIES:
                raise SystemExit(f"{label}: invalid difficulty {question['difficulty']!r}")
            if not isinstance(question["options"], list) or len(question["options"]) < 2:
                raise SystemExit(f"{label}: options must contain at least two choices")
            if not isinstance(question["answer"], int) or not (
                0 <= question["answer"] < len(question["options"])
            ):
                raise SystemExit(f"{label}: answer index is out of range")

        chapters.append(chapter)
    return chapters


def main() -> None:
    chapters = load_chapters()
    payload = json.dumps({"chapters": chapters}, ensure_ascii=False, indent=2)
    OUTPUT.write_text(
        "// Generated by build_quiz.py. Edit chNN.json files, then rebuild.\n"
        f"window.QUIZ_DATA = {payload};\n",
        encoding="utf-8",
    )
    question_count = sum(len(chapter["questions"]) for chapter in chapters)
    chapter_numbers = ", ".join(str(chapter["chapter"]) for chapter in chapters)
    print(
        f"Built {OUTPUT.name}: {len(chapters)} chapter(s) "
        f"({chapter_numbers}), {question_count} questions."
    )


if __name__ == "__main__":
    main()
